spring.application.name=school-academic-portal

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/school_academic_portal
spring.datasource.username=hamzaqureshi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true